data:
  data_path: "lhdm/data/mnist-inrs"
  dataset_type: "MNIST"
  class_label: 2
  sample_id: 1096
  batch_size: 32 # Increased batch size for better stability
  num_workers: 4
  sample_limit: 10
  split_ratio: [80, 10, 10]
  pin_memory: true
